export type StringKey = keyof typeof en;

export const en = {
  // Common
  appName: 'Nuvé',
  tagline: 'Wealth, Intelligently Managed',
  continue: 'Continue',
  back: 'Back',
  skip: 'Skip',
  done: 'Done',
  cancel: 'Cancel',
  save: 'Save',
  edit: 'Edit',
  delete: 'Delete',
  confirm: 'Confirm',
  loading: 'Loading...',
  retry: 'Retry',
  seeAll: 'See All',
  egp: 'EGP',
  year: 'Year',
  month: 'Month',

  // Onboarding
  welcomeTitle: 'Welcome to Nuvé',
  welcomeSubtitle: 'Institutional wealth management, made accessible for everyone.',
  getStarted: 'Get Started',
  signIn: 'Sign In',
  onboarding1Title: 'Build Towards Your Goals',
  onboarding1Body: 'Create personalized investment goals — home, education, Hajj, retirement — and watch your wealth grow.',
  onboarding2Title: 'Intelligent Portfolio Management',
  onboarding2Body: "Your portfolio adapts to market changes. We'll rebalance automatically and notify you when action is needed.",
  onboarding3Title: 'Total Transparency',
  onboarding3Body: 'See every fee before every transaction. No hidden charges, ever. Your money, your clarity.',

  // Risk Profiler
  riskProfilerTitle: 'Risk Assessment',
  riskProfilerSubtitle: 'Answer a few questions to receive your personalized risk profile.',
  riskResultTitle: 'Your Risk Profile',
  conservative: 'Conservative Saver',
  moderate: 'Balanced Investor',
  growth: 'Growth-Oriented',
  aggressive: 'Ambitious Investor',
  conservativeDesc: 'You prioritize capital protection. Your portfolio focuses on stability with lower but steady returns.',
  moderateDesc: 'You balance growth and security, comfortable with moderate market fluctuations.',
  growthDesc: 'You seek higher returns and are comfortable with market volatility over the long term.',
  aggressiveDesc: 'You pursue maximum growth and can tolerate significant market swings.',

  // Dashboard
  goodMorning: 'Good Morning',
  goodAfternoon: 'Good Afternoon',
  goodEvening: 'Good Evening',
  totalWealth: 'Total Wealth',
  totalReturn: 'Total Return',
  portfolioPerformance: 'Portfolio Performance',
  myGoals: 'My Goals',
  addGoal: 'Add Goal',
  quickInvest: 'Quick Invest',
  recentActivity: 'Recent Activity',

  // Goals
  homeGoal: 'Dream Home',
  educationGoal: "Children's Education",
  hajjGoal: 'Hajj Pilgrimage',
  retirementGoal: 'Retirement Fund',
  emergencyGoal: 'Emergency Fund',
  customGoal: 'Custom Goal',
  targetAmount: 'Target Amount',
  targetDate: 'Target Date',
  currentProgress: 'Current Progress',
  monthlyContribution: 'Monthly Contribution',
  projectedCompletion: 'Projected Completion',
  goalCreated: 'Goal Created',
  createGoal: 'Create Goal',
  goalName: 'Goal Name',

  // Portfolio
  portfolio: 'Portfolio',
  allocation: 'Allocation',
  performance: 'Performance',
  equity: 'EGX Stocks',
  bonds: 'Treasury Bills',
  gold: 'Gold',
  cash: 'Money Market',
  realestate: 'Real Estate',
  mutualFunds: 'Mutual Funds',
  rebalancing: 'Rebalancing',
  approveRebalance: 'Approve Rebalance',
  deferRebalance: 'Defer',
  rebalanceProposal: 'Rebalancing Proposal',
  driftDetected: 'Drift Detected',

  // Invest / Assets
  invest: 'Invest',
  assets: 'Assets',
  search: 'Search assets...',
  filterAll: 'All',
  minInvestment: 'Min. Investment',
  riskRating: 'Risk Rating',
  expectedReturn: 'Expected Return',
  buyNow: 'Buy Now',
  investAmount: 'Investment Amount',

  // Payments
  payments: 'Payments',
  instapay: 'InstaPay',
  vodafoneCash: 'Vodafone Cash',
  orangeCash: 'Orange Cash',
  fawry: 'Fawry',
  meeza: 'Meeza Card',
  bankTransfer: 'Bank Transfer',
  depositFunds: 'Deposit Funds',
  withdrawFunds: 'Withdraw Funds',
  recurringPlan: 'Recurring Plan',
  setupRecurring: 'Setup Recurring Investment',
  paymentAmount: 'Amount',
  paymentMethod: 'Payment Method',
  transactionFee: 'Transaction Fee',
  industryAvg: 'Industry Average',
  feeComparison: 'Fee Comparison',

  // Insights
  insights: 'Insights',
  portfolioHealth: 'Portfolio Health Score',
  inflationAdjusted: 'Inflation-Adjusted Returns',
  marketPulse: 'Market Pulse',
  dividends: 'Dividends',
  currencyExposure: 'Currency Exposure',
  nominalReturn: 'Nominal Return',
  realReturn: 'Real Return',
  inflationRate: 'Inflation Rate',
  healthExcellent: 'Excellent',
  healthGood: 'Good',
  healthFair: 'Fair',
  healthPoor: 'Needs Attention',

  // Scenario Modeling
  scenarioTitle: 'What If Scenarios',
  scenarioContribution: 'Monthly Contribution',
  scenarioTimeline: 'Timeline (Years)',
  scenarioInflation: 'Inflation Rate (%)',
  scenarioReturn: 'Expected Return (%)',
  scenarioWithdrawal: 'One-time Withdrawal',
  currentProjection: 'Current Projection',
  scenarioProjection: 'Scenario Projection',
  improvement: 'Improvement',
  decline: 'Decline',

  // FRA Compliance
  fraCompliance: 'FRA Compliance',
  licenseNumber: 'License Number',
  issueDate: 'Issue Date',
  lastRenewal: 'Last Renewal',
  lastAudit: 'Last Audit',
  complianceStatus: 'Status',
  fullCompliance: 'Full Compliance',
  verifyOnFRA: 'Verify on FRA Website',
  subsidiaries: 'Covered Subsidiaries',

  // Learning Hub
  learningHub: 'Learning Hub',
  articles: 'Articles',
  videos: 'Videos',
  calculators: 'Calculators',
  zakatCalc: 'Zakat Calculator',
  zakatResult: 'Zakat Due',
  nisab: 'Nisab Threshold',

  // Profile & Settings
  profile: 'Profile',
  settings: 'Settings',
  security: 'Security',
  biometric: 'Biometric Login',
  notifications: 'Notifications',
  language: 'Language',
  arabic: 'العربية',
  english: 'English',
  riskProfile: 'Risk Profile',
  retakeRisk: 'Retake Assessment',
  compliance: 'Compliance',
  auditTrail: 'Activity History',
  support: 'Support',
  advisorChat: 'Talk to an Advisor',
  signOut: 'Sign Out',
  version: 'Version',
  familyPortfolio: 'Family Portfolio',

  // Notifications
  notificationsTitle: 'Notifications',
  noNotifications: 'No notifications yet',
  markAllRead: 'Mark All Read',

  // Errors
  networkError: 'Unable to connect. Check your connection and try again.',
  genericError: 'Something went wrong. We are looking into it.',
  tryAgain: 'Try Again',
  noData: 'No data available',
};

export const ar: typeof en = {
  appName: 'نوفيه',
  tagline: 'الثروة، بذكاء',
  continue: 'استمر',
  back: 'رجوع',
  skip: 'تخطي',
  done: 'تم',
  cancel: 'إلغاء',
  save: 'حفظ',
  edit: 'تعديل',
  delete: 'حذف',
  confirm: 'تأكيد',
  loading: 'جاري التحميل...',
  retry: 'إعادة المحاولة',
  seeAll: 'عرض الكل',
  egp: 'ج.م',
  year: 'سنة',
  month: 'شهر',

  welcomeTitle: 'مرحباً بك في نوفيه',
  welcomeSubtitle: 'إدارة الثروات المؤسسية، في متناول الجميع.',
  getStarted: 'ابدأ الآن',
  signIn: 'تسجيل الدخول',
  onboarding1Title: 'ابنِ نحو أهدافك',
  onboarding1Body: 'أنشئ أهداف استثمارية مخصصة — منزل، تعليم، حج، تقاعد — وشاهد ثروتك تنمو.',
  onboarding2Title: 'إدارة محفظة ذكية',
  onboarding2Body: 'تتكيف محفظتك مع تغيرات السوق. سنعيد التوازن تلقائيًا ونخطرك عند الحاجة للتدخل.',
  onboarding3Title: 'شفافية تامة',
  onboarding3Body: 'اطّلع على كل رسوم قبل كل معاملة. لا رسوم خفية أبدًا. أموالك، وضوحك.',

  riskProfilerTitle: 'تقييم المخاطر',
  riskProfilerSubtitle: 'أجب على بعض الأسئلة للحصول على ملف المخاطر الخاص بك.',
  riskResultTitle: 'ملف المخاطر الخاص بك',
  conservative: 'مدخر محافظ',
  moderate: 'مستثمر متوازن',
  growth: 'موجه نحو النمو',
  aggressive: 'مستثمر طموح',
  conservativeDesc: 'تُولي الأولوية لحماية رأس المال. تركز محفظتك على الاستقرار مع عوائد ثابتة.',
  moderateDesc: 'توازن بين النمو والأمان، ومرتاح مع تقلبات السوق المعتدلة.',
  growthDesc: 'تسعى لعوائد أعلى وتتقبل تقلبات السوق على المدى البعيد.',
  aggressiveDesc: 'تسعى لأقصى نمو ويمكنك تحمل تذبذبات السوق الكبيرة.',

  goodMorning: 'صباح الخير',
  goodAfternoon: 'مساء الخير',
  goodEvening: 'مساء الخير',
  totalWealth: 'إجمالي الثروة',
  totalReturn: 'إجمالي العائد',
  portfolioPerformance: 'أداء المحفظة',
  myGoals: 'أهدافي',
  addGoal: 'إضافة هدف',
  quickInvest: 'استثمار سريع',
  recentActivity: 'النشاط الأخير',

  homeGoal: 'منزل الأحلام',
  educationGoal: 'تعليم الأبناء',
  hajjGoal: 'الحج المبارك',
  retirementGoal: 'صندوق التقاعد',
  emergencyGoal: 'صندوق الطوارئ',
  customGoal: 'هدف مخصص',
  targetAmount: 'المبلغ المستهدف',
  targetDate: 'التاريخ المستهدف',
  currentProgress: 'التقدم الحالي',
  monthlyContribution: 'المساهمة الشهرية',
  projectedCompletion: 'الإتمام المتوقع',
  goalCreated: 'تم إنشاء الهدف',
  createGoal: 'إنشاء هدف',
  goalName: 'اسم الهدف',

  portfolio: 'المحفظة',
  allocation: 'التوزيع',
  performance: 'الأداء',
  equity: 'أسهم البورصة',
  bonds: 'أذون الخزانة',
  gold: 'الذهب',
  cash: 'سوق المال',
  realestate: 'العقارات',
  mutualFunds: 'صناديق الاستثمار',
  rebalancing: 'إعادة التوازن',
  approveRebalance: 'الموافقة على إعادة التوازن',
  deferRebalance: 'تأجيل',
  rebalanceProposal: 'مقترح إعادة التوازن',
  driftDetected: 'انحراف محدد',

  invest: 'استثمار',
  assets: 'الأصول',
  search: 'بحث في الأصول...',
  filterAll: 'الكل',
  minInvestment: 'الحد الأدنى للاستثمار',
  riskRating: 'تقييم المخاطر',
  expectedReturn: 'العائد المتوقع',
  buyNow: 'اشتر الآن',
  investAmount: 'مبلغ الاستثمار',

  payments: 'المدفوعات',
  instapay: 'إنستاباي',
  vodafoneCash: 'فودافون كاش',
  orangeCash: 'أورانج كاش',
  fawry: 'فوري',
  meeza: 'ميزة',
  bankTransfer: 'تحويل بنكي',
  depositFunds: 'إيداع الأموال',
  withdrawFunds: 'سحب الأموال',
  recurringPlan: 'خطة دورية',
  setupRecurring: 'إعداد استثمار دوري',
  paymentAmount: 'المبلغ',
  paymentMethod: 'طريقة الدفع',
  transactionFee: 'رسوم المعاملة',
  industryAvg: 'متوسط الصناعة',
  feeComparison: 'مقارنة الرسوم',

  insights: 'الرؤى',
  portfolioHealth: 'نقاط صحة المحفظة',
  inflationAdjusted: 'العوائد معدلة التضخم',
  marketPulse: 'نبض السوق',
  dividends: 'الأرباح الموزعة',
  currencyExposure: 'التعرض للعملات',
  nominalReturn: 'العائد الاسمي',
  realReturn: 'العائد الحقيقي',
  inflationRate: 'معدل التضخم',
  healthExcellent: 'ممتاز',
  healthGood: 'جيد',
  healthFair: 'مقبول',
  healthPoor: 'يحتاج اهتمام',

  scenarioTitle: 'سيناريوهات افتراضية',
  scenarioContribution: 'المساهمة الشهرية',
  scenarioTimeline: 'الأفق الزمني (سنوات)',
  scenarioInflation: 'معدل التضخم (%)',
  scenarioReturn: 'العائد المتوقع (%)',
  scenarioWithdrawal: 'سحب لمرة واحدة',
  currentProjection: 'التوقع الحالي',
  scenarioProjection: 'توقع السيناريو',
  improvement: 'تحسن',
  decline: 'انخفاض',

  fraCompliance: 'امتثال هيئة الرقابة المالية',
  licenseNumber: 'رقم الترخيص',
  issueDate: 'تاريخ الإصدار',
  lastRenewal: 'آخر تجديد',
  lastAudit: 'آخر تدقيق',
  complianceStatus: 'الحالة',
  fullCompliance: 'امتثال كامل',
  verifyOnFRA: 'التحقق على موقع HFR',
  subsidiaries: 'الشركات التابعة المشمولة',

  learningHub: 'مركز التعلم',
  articles: 'المقالات',
  videos: 'مقاطع الفيديو',
  calculators: 'الحاسبات',
  zakatCalc: 'حاسبة الزكاة',
  zakatResult: 'الزكاة المستحقة',
  nisab: 'حد النصاب',

  profile: 'الملف الشخصي',
  settings: 'الإعدادات',
  security: 'الأمان',
  biometric: 'تسجيل دخول بيومتري',
  notifications: 'الإشعارات',
  language: 'اللغة',
  arabic: 'العربية',
  english: 'English',
  riskProfile: 'ملف المخاطر',
  retakeRisk: 'إعادة التقييم',
  compliance: 'الامتثال',
  auditTrail: 'سجل النشاط',
  support: 'الدعم',
  advisorChat: 'تحدث مع مستشار',
  signOut: 'تسجيل الخروج',
  version: 'الإصدار',
  familyPortfolio: 'محفظة الأسرة',

  notificationsTitle: 'الإشعارات',
  noNotifications: 'لا توجد إشعارات بعد',
  markAllRead: 'تحديد الكل كمقروء',

  networkError: 'تعذر الاتصال. تحقق من اتصالك وحاول مرة أخرى.',
  genericError: 'حدث خطأ ما. نحن نحقق في الأمر.',
  tryAgain: 'حاول مرة أخرى',
  noData: 'لا توجد بيانات متاحة',
};

export type Strings = typeof en;
